### ISSUE TITLE
Not working as of 2021-05-06

### ISSUE THREAD

**Issue by picorealm** [tiansh/block-twitter-promoted#2]
I'm sorry but this addon is no longer working with Twitter as of 2021-05-06.  Prior to this there were no promoted tweets in the TL however since today they are showing up.

**Comment by tiansh** [comment]
Seems website had upgrade their React to a newer version. As the result, the previous way to detect Redux Store had failed. I had tried to make some modify to fit this behavior. The newer version should be available on AMO soon. Fell free to reopen this issue if it still not works after upgrade to the newer version.
